# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.cors.action_listener:
        class: AppBundle\Service\CorsHeaderService
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    send_sms_service:
        class: JustMeet\AppBundle\Consumer\SendSmsConsumer
        arguments:
            - "%nexmo%"

    utility.jsonrequest.action_listener:
        class: JustMeet\AppBundle\EventListener\JsonListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    kernel.listener.apiaccess:
        class: JustMeet\AppBundle\EventListener\ErrorListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

